# Generated by Django 3.1.4 on 2020-12-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=300)),
                ('Employee_PhNo', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employer_Name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('Employer_PhNo', models.CharField(max_length=300)),
                ('Employer_Email', models.EmailField(max_length=300)),
            ],
        ),
    ]
