# Generated by Django 3.1.4 on 2020-12-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Emp_ID',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
