# Generated by Django 3.1.4 on 2020-12-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTC', '0002_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Emp_Job_Requirement',
            field=models.CharField(default='Hello', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Emp_Mail',
            field=models.EmailField(default='s@gmail.com', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='Employer_BizModel',
            field=models.CharField(default='Biz_Model', max_length=300),
            preserve_default=False,
        ),
    ]
